name: SonarCloud CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake gcovr unzip curl

      - name: Download Sonar build-wrapper
        run: |
          curl -sSLo bw.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -q bw.zip
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64

      - name: Configure
        run: |
          rm -rf build bw-output
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc

      - name: Build (wrapped) + run + generate coverage
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build
          ./build/coverage_main
          gcovr -r . --filter src --sonarqube -o coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=romain7278
            -Dsonar.projectKey=Romain7278_IwIP-clone
            -Dsonar.sources=src
            -Dsonar.exclusions=test/**,doc/**,**/*.md
            -Dsonar.cfamily.build-wrapper-output=bw-output
            -Dsonar.coverageReportPaths=coverage.xml